### ISSUE TITLE
Add documentation for project

### ISSUE THREAD

**Issue by cguertin14** [ClubCedille/mattermost2discord#23]
* Add docs for bot setup in Mattermost
* Add docs for how is webhook triggered in Mattermost
* Other docs.

**Comment by SonOfLope** [comment]
@cguertin14 est-ce que je doit expliquer le set up du api sur le web server & sur le docker hub repo?

**Comment by cguertin14** [comment]
> @cguertin14 est-ce que je doit expliquer le set up du api sur le web server & sur le docker hub repo?

Pas besoin :)
