### ISSUE TITLE
Outgoing webhook config sur Mattermost

### ISSUE THREAD

**Issue by cguertin14** [ClubCedille/mattermost2discord#5]
- Triggering d'une webhook qui enverra le message de Mattermost vers Discord (HTTP POST Request)
- Établir la communication entre Mattermost et votre service

Référence: https://docs.mattermost.com/developer/webhooks-outgoing.html

**Comment by cguertin14** [comment]
Sous-domaine qui sera utilisé pour le Callback de la webhook: https://mmdisc.cedille.site

**Comment by berbiche** [comment]
@cguertin14 on devrait utiliser un sous-sous-domaine, genre `https://mmdisc.d.cedille.site`, où `d.cedille.site` serait pour le stuff de développement ou whatever?
@starcraft66 tu en penses quoi?

**Comment by cguertin14** [comment]
Ok pour le développement, mais pour callback officiel en prod on garde celui que j'ai écris plus haut
