### ISSUE TITLE
Automatisation des releases Docker + Github avec GoReleaser

### ISSUE THREAD

**Issue by cguertin14** [ClubCedille/mattermost2discord#9]
- Build & Push docker images vers GCR
- Automatisation de releases github
- Référence: https://goreleaser.com

**Comment by cguertin14** [comment]
L'image peut être stockée sur Dockerhub puisque le projet est ouvert.
Les variables d'environnement suivantes peuvent être utilisées dans le CI:

* `DOCKER_HUB_ACCESS_TOKEN`
* `DOCKER_HUB_USERNAME`

L'image sera stockée dans la registry ouverte de CEDILLE: https://hub.docker.com/orgs/clubcedille

**Comment by Vboivin** [comment]
Je vais travailler là-dessus ce weekend
